#! /bin/bash

if ! [ $# -eq 1 ]; then
    echo -e "USAGE:\n ./generator sshkey_of_the_repository" >&2
    exit 84
fi

if ! git clone "$1" tmp/ &> /dev/null; then
    echo "Error: cannot find $1!"
    exit 84
fi

cd tmp/

commit_message="[~] Update the README.md"

if ! [ -e tmp/README.md ]; then
    commit_message="[+] Add the README.md"
fi

read -ep "What is the name of the project? -> " project_name

if [ -z "$project_name" ]; then
    project_name="$1"
fi

echo -e "# $project_name\n" > README.md

read -ep "What module the project is part of? (empty for none) -> " module_name

if ! [ -z "$module_name" ]; then
    read -ep "What grade do you acquired for $module_name? (empty if the module is not finished) -> " module_grade
    if [ -z "$module_grade" ]; then
        module_grade="N/A"
    fi
    echo -e "## Module: $module_name (Grade: $module_grade)\n" >> README.md
fi

read -ep "What is the description for this project? (empty for none) -> " project_desc

if ! [ -z "$project_desc" ]; then
    echo -e "## Project Description\n $project_desc\n" >> README.md
fi

while true; do
    read -ep "Add the tests (empty for stop) -> " tests_str
    if [ -z "$tests_str" ]; then
        break
    fi
    python3 ../main.py "$tests_str" >> README.md
    echo >> README.md
done

git add README.md &> /dev/null

git commit -m "$commit_message" &> /dev/null

git push -f origin main &> /dev/null

cd - &> /dev/null

rm -rf tmp/
